export const CARD_ADD_ITEM = 'CARD_ADD_ITEM'
export const CARD_REMOVE_ITEM = 'CARD_REMOVE_ITEM'
export const CARD_SAVE_SHPPING_ADDRESS = 'CARD_SAVE_SHPPING_ADDRESS'

export const CART_SAVE_PAYMENT_METHOD = 'CART_SAVE_PAYMENT_METHOD'

export const CART_CLEAR_ITEMS ='CART_CLEAR_ITEMS'